version: '3'

services:
    nginx:
        image: nginx:latest
        volumes:
            -   ./:/var/www
            -   ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            -   "8876:80"
        depends_on:
            -   app
        container_name: project_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            -   ./:/var/www
            -   /var/run/docker.sock:/var/run/docker.sock
            -   ./code-share:/var/www/code
        container_name: project_app

    postgres:
        image: postgres:15
        restart: always
        environment:
            POSTGRES_DB: SilicsDB
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: parol372
        volumes:
            -  pgdata:/var/lib/postgresql/data
        ports:
            -  "5433:5432"
        container_name: project_postgres

    php-runner:
        image: php:8.2-fpm
        volumes:
            - ./code-share:/var/www/code
        working_dir: /var/www
        container_name: php_runner

    python-runner:
        build:
            context: .
            dockerfile: _docker/python/Dockerfile
        volumes:
            -   ./code-share:/var/www/code
        working_dir: /var/www
        container_name: python_runner
        ports:
            -   "5001:5001"

volumes:
    pgdata:
    code-share:
